CREATE TABLE IF NOT EXISTS disk (
  diskid IDENTITY NOT NULL PRIMARY KEY,
  filepath VARCHAR(500) NOT NULL,
  filename VARCHAR(100) NOT NULL,
  label VARCHAR(32) DEFAULT NULL,
  updated TIMESTAMP NOT NULL,
  imagetype INTEGER NOT NULL,
  errors INTEGER DEFAULT NULL,
  warnings INTEGER DEFAULT NULL,
  hostname VARCHAR(256) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS diskfile (
  fileid IDENTITY NOT NULL PRIMARY KEY,
  diskid long NOT NULL,
  name VARCHAR(32) NOT NULL,
  filetype INTEGER NOT NULL DEFAULT 1,
  size INTEGER NOT NULL DEFAULT 0,
  filenum INTEGER NOT NULL DEFAULT 0,
  flags INTEGER NOT NULL DEFAULT 0,
  namebytes BLOB,
  FOREIGN KEY (diskid) REFERENCES disk(diskid) ON DELETE CASCADE
);
